const Withdrawhistory = [
        {
          srno:"1",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Success",
        },
        {
          srno:"2",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
        {
          srno:"3",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
        {
          srno:"4",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Success",
        },
        {
          srno:"5",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
        {
          srno:"6",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Success",
        },
        {
          srno:"7",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
        {
          srno:"8",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
        {
          srno:"9",
          paymode:"gamebet",
          date:"21/05/2023",
          points:"107",
          closeing:"2587",
          status:"Pending",
        },
       
        
     ];
 
export default Withdrawhistory;