const marketnamedata =[
  {
    title:"Market Name",
    path:"details",
    market:"Market Close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
    previousresult:"255",
    todayresult:"25",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market Open",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
    
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"24",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"25",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"14",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"80",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"25",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"12",
  },
  {
    title:"Market Name",
    path:"details",
    market:"Market close",
    opentime:"open-10.45 AM",
    closetime:"close-10.45 AM",
     previousresult:"255",
    todayresult:"25",
  },
];
export default marketnamedata;